//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinHRTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emailUser {
            get {
                return ((string)(this["emailUser"]));
            }
            set {
                this["emailUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emailPass {
            get {
                return ((string)(this["emailPass"]));
            }
            set {
                this["emailPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Users,OU=CardinalPeak,DC=cardinalpeak,DC=com")]
        public string adPath {
            get {
                return ((string)(this["adPath"]));
            }
            set {
                this["adPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cardinalpeak.com")]
        public string adDomain {
            get {
                return ((string)(this["adDomain"]));
            }
            set {
                this["adDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cpsysadmin")]
        public string adUser {
            get {
                return ((string)(this["adUser"]));
            }
            set {
                this["adUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4#a7yaof")]
        public string adPass {
            get {
                return ((string)(this["adPass"]));
            }
            set {
                this["adPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OS-DCPP102")]
        public string adPDC {
            get {
                return ((string)(this["adPDC"]));
            }
            set {
                this["adPDC"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.harvestapp.com/v2/users/")]
        public string harvestURL {
            get {
                return ((string)(this["harvestURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOGZiOWFkMDkwYTYxYTJkNDk5NGNlODg5NTk0MGYzYzhjNzc5NDRhZTM3OTI0OTM3YjIwMGUwZTQ0ZmRhNDExODU4NjQxMjg2OTY2MzRjOTIiLCJpYXQiOjE2NDQ1MjgwNjAsIm5iZiI6MTY0NDUyODA2MCwiZXhwIjoyMjc1NjgwMDYwLCJzdWIiOiIxODkiLCJzY29wZXMiOltdfQ.y0L7iMyeR89N0oot-daTl42NmSWxjoWcrfXiQFpprB_TGJ9qTr0g0WWwJYEB2syrxOmVwZnxSzV1w6OxTbOArbixcTsL_Ra0IIYj66iyxiOhYr4n_aIy8PqVuAtZxqjPnHDE5BZDHzC7N0MUvplQAV752MCvCKUyVieia7sfxKl_voqfJT8bM-JD61q5s3af4dJXT1GG-e37TKZiM1VhJhd2u1t2-PEhecpn339cMEp-OHju50u_D-z_xdBb4r92Y_ktpr60-QndavazwTqsvyZRNzQ6SnGezWDKcNntq1N4G3Zrd-FxyCD0BgE1PD3iBnNP99-CMgCCeD9xhwl0C-_dgAZsPlcS7hO82qy63yPtzEF71efZkN8JmA5hbzOVOWHSdqN3HhJCHlQiNSPnT9b4U9E-Y4Em25yjMBiRYwkRAY3zNwryAStGwCBz0XPW19AvPTiD_5FvVkqfj9rVtT10TRcyRSOZQ4CI49oi7644XglAChspMXIfgsjHCG0zbB9X2tTsUebtOTEpYbAS0EA3OeaKhSUIOVyDq2z6iTf2a49p-MlLDEcVcL5-umknFwqLJBfOEJHVtz0lZB5kqqh2d-PiEfXsyQqlmo0IpDubqnrQtS6HfOQ6K5Hpdc_zDKhI6tUPVfpbE8IAdmmkhxwhZfRqfuCGcK473sU9ubE")]
        public string snipeKey {
            get {
                return ((string)(this["snipeKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bearer 2915176.pt.Kc2sAv-Q394QYxFkjOxL6_Zpxu4GsDmpQ59SWjtv903-UOi0K15Eq03nQVX4XTG" +
            "xzVQ6IhZW5YO0IxgzBStvyw")]
        public string harvestKey {
            get {
                return ((string)(this["harvestKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cardinalpeak.snipe-it.io/api/v1")]
        public string snipeURL {
            get {
                return ((string)(this["snipeURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("347970")]
        public string harvestID {
            get {
                return ((string)(this["harvestID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dkvpn")]
        public string gcdsUser {
            get {
                return ((string)(this["gcdsUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("!Tech2010!@")]
        public string gcdsPass {
            get {
                return ((string)(this["gcdsPass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lastpass.com/enterpriseapi.php")]
        public string lastpassURL {
            get {
                return ((string)(this["lastpassURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8252606")]
        public string lastpassID {
            get {
                return ((string)(this["lastpassID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4e3d05b80daf81ade27159c11ff9d8d20129bdb5100036a3ce99251704680e52")]
        public string lastpassKey {
            get {
                return ((string)(this["lastpassKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AC7d8d843ce9d9c7783055ea0e871361f6")]
        public string twilioID {
            get {
                return ((string)(this["twilioID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4dc116d8332935d8a4bd503664b9069b")]
        public string twilioToken {
            get {
                return ((string)(this["twilioToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nwptaevfpsvxogwu")]
        public string gmaillAppPass {
            get {
                return ((string)(this["gmaillAppPass"]));
            }
        }
    }
}
